name: Build Binaries

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Prevent concurrent runs on the same ref, cancelling in-progress jobs
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Clean previous builds
        # Use bash to dispatch to the right shell
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            # PowerShell clean, ignoring missing dirs
            pwsh -Command "Remove-Item -Path build,dist -Recurse -Force -ErrorAction SilentlyContinue"
          else
            # Bash clean
            rm -rf build/ dist/
          fi

      - name: Build executable
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            pyinstaller --onefile \
              --add-data "config;config" \
              --add-data "static;static" \
              main.py
          else
            pyinstaller --onefile \
              --add-data "config:config" \
              --add-data "static:static" \
              main.py
          fi

      - name: Upload Windows EXE
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: TestReportGenerator-windows
          path: dist/main.exe

      - name: Upload Linux Binary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: TestReportGenerator-linux
          path: dist/main
