name: Build Binaries (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: windows-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: windows-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Clean previous builds
        shell: pwsh
        run: |
          Remove-Item -Path build,dist -Recurse -Force -ErrorAction SilentlyContinue

      - name: Build Windows executable
        shell: pwsh
        run: |
          pyinstaller --onefile `
            --add-data "config;config" `
            --add-data "static;static" `
            main.py

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: TestReportGenerator-windows
          path: dist/main.exe
