name: Lint & Type-Checking

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Flake8 & Mypy
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy

      - name: Run flake8
        run: flake8 .

      - name: Run mypy
        run: mypy .
